server:
  port: 9006
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exemplo_endereco_bd?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update